# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 718f08cd406832cbbfea2f47bfa5c2662e0d49827d2cd678aa087321674a906d4e92fe255be9197b7e5079cb6e0ffc3a027eefc41bfb2b59a7fd89c1bf46faf8

test:
  secret_key_base: a5139303184c57ad5a8573f06c8081c37a873b6274aa2bf5e1a0053af2c420369953e5925cbc693b76dce06db8f34eecb7ea6b77eb7cc45b770fa1895470dea4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
